# Generated by Django 2.0 on 2018-02-26 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu_max_usage',
            field=models.IntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='disk_max_percent',
            field=models.IntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='end_hour',
            field=models.IntegerField(blank=True, default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='max_CPUs',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram_max_usage',
            field=models.IntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='start_hour',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
