# Generated by Django 2.0.3 on 2018-03-28 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='uid',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='UID must be 10 hex characters', regex='^\\w{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Investor'), (2, 'Contributor'), (3, 'Both')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
