# Generated by Django 2.0 on 2018-02-28 01:49

import api.models.project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180225_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='area1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='area2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='platforms',
            field=api.models.project.PlatformField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sponsors',
            field=api.models.project.SeparatedValuesField(default=''),
            preserve_default=False,
        ),
    ]
