# Generated by Django 2.0 on 2018-02-28 01:50

import api.models.project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180227_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='platforms',
            field=api.models.project.PlatformField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsors',
            field=api.models.project.SeparatedValuesField(null=True),
        ),
    ]
