# Generated by Django 2.0.3 on 2018-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180403_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='user',
            name='data_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='whitepaper',
            field=models.BooleanField(default=False),
        ),
    ]
