# Generated by Django 2.0.3 on 2018-04-08 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180406_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TE', 'Telegram'), ('LN', 'Linkedin'), ('YT', 'Youtube'), ('BT', 'Bitcoin Talk'), ('RD', 'Reddit'), ('OR', 'Other')], default='OR', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='ether_addr',
            field=models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Ether address length must be 42 characters', regex='^\\w{42}$')]),
        ),
    ]
