# Generated by Django 2.0 on 2018-03-09 23:47

import api.models.project
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180227_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platforms',
            field=api.models.project.PlatformField(max_length=40, null=True),
        ),
    ]
