# Generated by Django 2.0 on 2018-03-10 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180309_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=40, validators=[django.core.validators.RegexValidator(code='nomatch', message='UID length (from SHA1) must be 40 characters', regex='^\\w{40}$')]),
        ),
    ]
