# Generated by Django 2.0.3 on 2018-04-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180408_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='over_18',
        ),
    ]
