# Generated by Django 2.0 on 2018-03-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180309_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='cpu_max_usage',
            new_name='cpu_max_percent',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='ram_max_usage',
            new_name='ram_max_percent',
        ),
    ]
