# Generated by Django 2.0.3 on 2018-04-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_is_api_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TE', 'Telegram'), ('LN', 'Linkedin'), ('YT', 'Youtube'), ('MD', 'Medium'), ('BT', 'Bitcoin Talk'), ('RD', 'Reddit'), ('OR', 'Other')], default='OR', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
