# Generated by Django 2.0.3 on 2018-03-15 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180312_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField()),
                ('actionable', models.BooleanField(default=False)),
                ('markdown', models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)])),
            ],
            options={
                'db_table': 'api_sale',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bitcoin_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reddit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='steemit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_max_percent',
            field=models.SmallIntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='disk_max_percent',
            field=models.SmallIntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='end_hour',
            field=models.SmallIntegerField(blank=True, default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='max_CPUs',
            field=models.SmallIntegerField(blank=True, default=2, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram_max_percent',
            field=models.SmallIntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='start_hour',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
