# Generated by Django 2.0.3 on 2018-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180314_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='street_addr',
            new_name='street_addr1',
        ),
        migrations.AddField(
            model_name='user',
            name='street_addr2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
