# Generated by Django 2.0.3 on 2018-04-10 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180410_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='State ID length must be 2 characters', regex='^\\w{2}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
