# Generated by Django 2.0.3 on 2018-03-18 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180315_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TE', 'Telegram'), ('LN', 'Linkedin'), ('BT', 'Bitcoin Talk'), ('RD', 'Reddit'), ('OR', 'Other')], default='OR', max_length=2)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_social_media_post',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
