# Generated by Django 2.0.3 on 2018-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180410_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('linkedin', 'Linkedin'), ('youtube', 'Youtube'), ('medium', 'Medium'), ('bitcoin_talk', 'Bitcoin Talk'), ('reddit', 'Reddit'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
