# Generated by Django 2.0.3 on 2018-04-11 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180410_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='device',
            name='start_hour',
        ),
        migrations.AddField(
            model_name='device',
            name='fri_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='fri_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='mon_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='mon_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='sat_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='sat_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='sun_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='sun_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='thurs_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='thurs_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='tues_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='tues_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='wed_end',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='wed_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
