# Generated by Django 2.0.3 on 2018-04-12 02:48

import api.models.file
import api.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180411_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to=api.models.file.get_upload_path)),
                ('file_type', models.CharField(choices=[('SF', 'Selfie'), ('ID', 'ID File')], default='SF', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='past_projects',
        ),
        migrations.AddField(
            model_name='device',
            name='net_max_bytes_down',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='device',
            name='net_max_bytes_up',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='device',
            name='use_mem_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='fri_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='fri_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='mon_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='mon_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='sat_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='sat_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='sun_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='sun_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='thurs_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='thurs_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='tues_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='tues_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, on_delete='CASCADE', related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='wed_end',
            field=models.SmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='wed_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
