# Generated by Django 2.0.3 on 2018-04-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180411_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_type',
            new_name='filetype',
        ),
    ]
