# Generated by Django 2.0.3 on 2018-04-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180411_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('SF', 'Selfie'), ('ID', 'ID File')], default='SF', max_length=2)
        ),
    ]
