# Generated by Django 2.0.3 on 2018-04-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180411_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('SF', 'Selfie'), ('ID', 'ID File')], default='NO', max_length=2),
        ),
    ]
