# Generated by Django 2.0.3 on 2018-04-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180412_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mimetype',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/html', 'HTML'), ('text/css', 'CSS'), ('text/javascript', 'Javascript'), ('image/gif', 'GIF'), ('image/png', 'PNG'), ('image/png', 'PNG'), ('image/jpeg', 'JPEG'), ('image/bmp', 'BMP'), ('image/webp', 'WEBP'), ('audio/midi', 'MIDI'), ('audio/mpeg', 'MPEG'), ('audio/webm', 'WEBM'), ('audio/ogg', 'OGG'), ('audio/wav', 'WAV'), ('video/webm', 'WEBM'), ('video/ogg', 'OGG'), ('application/octet-stream', 'Octet Stream'), ('application/pkcs12', 'PKCS12'), ('application/vnd.mspowerpoint', 'MS Powerpoint'), ('application/xhtml+xml', 'XHTML XML'), ('application/xml', 'XML'), ('application/pdf', 'PDF'), ('multipart/form-data', 'Form Data'), ('multipart/byteranges', 'Byte Ranges')], default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('NO', 'None'), ('SF', 'Selfie'), ('ID', 'ID File')], default='NO', max_length=2),
        ),
    ]
