# Generated by Django 2.0.3 on 2018-04-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180422_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.EmailField(max_length=254)),
                ('header', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('footer', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(related_name='emails', to='api.File')),
            ],
        ),
    ]
