# Generated by Django 2.0.3 on 2018-04-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='times_sent',
            field=models.SmallIntegerField(default=0),
        ),
    ]
