# Generated by Django 2.0.3 on 2018-05-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180422_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
