# Generated by Django 2.0.3 on 2018-05-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180501_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, related_name='emails', to='api.File'),
        ),
    ]
