# Generated by Django 2.0.3 on 2018-05-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180501_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='email',
            name='header',
        ),
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='emails', to='api.File'),
        ),
    ]
